### ISSUE TITLE
1.7.2 can't be loaded / git-Bukkit-930a59c (MC: 1.8.8)

### ISSUE THREAD

**Issue by rschmied** [zack6849/SuperLogger#10]
hmm... am I the only one? Dropped jar in to plugin folder and get this at server start:
```

[23:01:24 INFO]: This server is running CraftBukkit version git-Bukkit-930a59c (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[23:01:24 ERROR]: Could not load 'plugins/SuperLogger-v1.7.2.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/zack6849/superlogger/Main : Unsupported major.minor version 52.0

```

**Comment by Rhmul** [comment]
I am getting the exact same error. I updated the java on the server, and noting changed

**Comment by zack6849** [comment]
then you didn't update your java correctly, see this: http://stackoverflow.com/a/23249825
My code is compiled for java 8, your server is likely running java 7.

**Comment by zack6849** [comment]
Seeing as you haven't replied in 2 months, i'm going to assume this is fixed and close it.
