### ISSUE TITLE
Not logging chat

### ISSUE THREAD

**Issue by Okervill** [zack6849/SuperLogger#11]
Hi there,

Just started using your plugin. It logs everything for me except chat strangely
Config file below

```
auto-update: true
update-notify: true
debug: false
log:
  commands: true
  #do we check if a command is even a real command before we log it?
  check-command-exists: false
  chat: true
  join: true
  quit: true
  kick: true
  death: true
  #do we log disallowed connections? (banned, not whitelisted, full server, etc)
  failed-connections: true
  player-ip: true
  player-uuid: false
  coordinates: true
#a list of commands ignored by superlogger, for privacy reasons.
blacklist:
  - 'login'
  - 'register'
```

**Comment by Okervill** [comment]
^ Unsure why, i had been reloading the server... when i restarted the server it began working

**Comment by zack6849** [comment]
Thanks for the update, i was going to say, this plugin hasn't needed any updated for maintenance in quite a while and is generally pretty stable, so i can't imagine why it wouldn't log chat.
