### ISSUE TITLE
Doesn't create folder for each day 

### ISSUE THREAD

**Issue by Okervill** [zack6849/SuperLogger#4]
Hi, I've been using Super Logger for 4 days now and it has a folder for the 24th (the first day I got it) and that's it. It's never created a folder for any other date and it's just storing every line of chat in one massive text file. Any help?

**Comment by zack6849** [comment]
Post your config file?

**Comment by Okervill** [comment]
auto-update: true
update-notify: true
debug: false
log:
  commands: true
  #do we check if a command is even a real command before we log it?
  check-command-exists: false
  chat: true
  join: true
  quit: true
  kick: true
  death: true
  #do we log disallowed connections? (banned, not whitelisted, full server, etc)
  failed-connections: true
  player-ip: false
  player-uuid: false
  coordinates: true
#a list of commands ignored by superlogger, for privacy reasons.
blacklist:
  - 'login'
  - 'register'

**Comment by Okervill** [comment]
I also just realised that the deaths log has been put into the a folder for the 25th by itself. So chat, connections and commands are in the 24th folder and deaths are in the 25th folder

**Comment by zack6849** [comment]
Can't believe this bug went unnoticed so long, thanks for pointing this out, i'm fixing it as we speak.

**Comment by Okervill** [comment]
Oh cheers :)  thanks for getting onto it as quick as you have!

**Comment by zack6849** [comment]
Just an update, the auto-updater the plugin previously used is no longer updated or usable so i'm having to re-implement a new updating system, hence the delay.

**Comment by zack6849** [comment]
Fixed in 6c288423a509d447b98d6c780357da86df98f807

**Comment by zack6849** [comment]
Forgot to mention, just so you know you can get the new version [**here**](https://ci.notoriousdev.com/job/SuperLogger/lastSuccessfulBuild/artifact/build/libs/SuperLogger-v1.7.jar) or from bukkit's page for the plugin
